auto: true
permalink: /:title.html
markdown: kramdown

uri: http://buddypress.coursewa.re
author: BuddyPress Courseware
email: stas@coursewa.re
title: BuddyPress Courseware
tagline: Social LMS
face: https://secure.gravatar.com/avatar/73dac6784c6ff5bb07614eed34226e32?s=70
face_alt: BuddyPress Logo
intro: |
  <a href="http://buddypress.org/">BuddyPress</a>
  is an open source social network project.
  <br>
  <a href="http://wordpress.org/extend/plugins/buddypress-courseware/">
  BuddyPress Courseware</a> is a learning management system
  built to make teaching social again.
  <br>
  Also check out <a href="http://open.coursewa.re">
  The Courseware Project</a> we've open sourced in Nov 2013.
  <hr>
  <div class="book">
    <img src="https://www.packtpub.com/sites/default/files/imagecache/productview/8208OS_1.jpg" alt="WordPress for Education cover" class="aligncenter">
    <a href="http://www.packtpub.com/wordpress-interactive-engaging-elearning-education-websites/book">Buy the book from Packt Pub.</a>
  </div>
  BuddyPress Courseware now is unmaintained, 2 years after the
  <a href="http://google-melange.appspot.com/">
  Google Summer of Code</a> programme in 2010 and 2011 (accepted and mentored
  by <a href="http://wordpress.org/">WordPress</a>
  and <a href="http://scholarpress.net/">ScholarPress</a> mentors).

button_left: |
  <a href="http://wordpress.org/extend/plugins/buddypress-courseware/">
  WordPress.org <strong>Project</strong></a>
button_mid: |
  <a href="http://buddypress.org/community/groups/buddypress-courseware/forum/">
  Support <strong>Forums</strong></a>
button_right: <a href="/handbook.html">Project <strong>Handbook</strong></a>
copyright_note: |
  Most of the content is under
  <a href="http://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>
  license.
